In [43]:
import numpy as khan
a=khan.array([1,3,2,4,6,5,7])
print(a)



[1 3 2 4 6 5 7]


In [44]:
a.size

7

In [45]:
a.itemsize

4

In [46]:
a.min()

1

In [47]:
a.max()

7

In [48]:
a.ndim

1

In [49]:
print(a[0])

1


In [50]:
print(a[3])

4


In [51]:
type(a)

numpy.ndarray

In [52]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7])

In [53]:
import numpy as riz
r=riz.array([[1,2,3,4],[5,6,7,8]])
print(r)

[[1 2 3 4]
 [5 6 7 8]]


In [54]:
type(r)

numpy.ndarray

In [41]:
r.ndim

2

In [42]:
print(r[0,0])

1


# Three Dim Array 

In [85]:
import numpy as hhh
a=hhh.array([[[1,2,3,4,5],[9,8,7,6,10],[11,12,13,14,15]]])
print(a)

[[[ 1  2  3  4  5]
  [ 9  8  7  6 10]
  [11 12 13 14 15]]]


In [91]:
print(a[0,1,2])

7


In [92]:
hhh.sort(a)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [93]:
hhh.min(a)

1

In [95]:
hhh.max(a)

15

In [99]:
a.max()

15

In [101]:
a.size

15

In [102]:
a.itemsize

4

In [103]:
import numpy as np
a=np.array([11.2,23.3,12.4])
print(a)

[11.2 23.3 12.4]


In [104]:
a.itemsize

8

In [113]:
a=8*8
b=4*8
print(a)
print(b)

64
32


In [127]:
import numpy as np
a=np.array(["kam"])
print(a)

['kam']


In [128]:
a.itemsize

12

In [120]:
a=1024*1024*1024
print(a)

1073741824


In [121]:
c=a/8
print(c)

134217728.0


In [122]:
d=c*8
print(d)

1073741824.0


# Data Types String

In [3]:
import numpy as k
a=k.array(["riz","kam","jam"])
print(a)

['riz' 'kam' 'jam']


In [4]:
a.itemsize

12

In [5]:
a.max

<function ndarray.max>

In [6]:
a.size

3

In [14]:
print(a[1])

kam


In [13]:
a.ndim

1

In [16]:
k.sort(a)

array(['jam', 'kam', 'riz'], dtype='<U3')

In [18]:
type(a)

numpy.ndarray

# Data Types Float

In [20]:
import numpy as per
a=per.array([1.2,2.1,3.5,5.4])
print(a)

[1.2 2.1 3.5 5.4]


In [21]:
a.size

4

In [22]:
a.itemsize

8

In [24]:
per.sort(a)

array([1.2, 2.1, 3.5, 5.4])

In [26]:
a.max()

5.4

In [27]:
a.min()

1.2

In [30]:
print(a[0])

1.2


In [31]:
print(a[2])

3.5


# how to add numpy arr


In [54]:
import numpy as ja
a=ja.array([1,2,3,4,5,6,7,8,9])
print(a[0]+a[1]+a[1]+a[1])

7


In [51]:
print(a[3]-a[2])

1


In [52]:
print(a[1]*a[2])

6


In [53]:
print(a[6]/a[2])

2.3333333333333335


# copy array in numpy

In [58]:
import numpy as swat
khan=swat.array([1,2,3,4,5,6,7,8,9])
print(khan)

[1 2 3 4 5 6 7 8 9]


In [59]:
import numpy as np
k=khan.copy()
print(k)

[1 2 3 4 5 6 7 8 9]


In [61]:
import numpy as swat
khan=swat.array([1,2,3,4,5,6,7,8,9])
_copy=khan.copy()
_copy[4]=10

print(khan)
print(_copy)

[1 2 3 4 5 6 7 8 9]
[ 1  2  3  4 10  6  7  8  9]


In [72]:
import numpy as riz
a=riz.array([8,7,6,5,4,3,2,1])
p=a.copy()
print(a)
riz.sort(p)
print(p)


[8 7 6 5 4 3 2 1]
[8 7 6 5 4 3 2 1]


In [73]:
riz.sort(p)
print(p)

[8 7 6 5 4 3 2 1]


# view in numpy 

In [63]:
import numpy as rizwan
a=rizwan.array([1,4,3,2,5,6,7,8])
_view=a.view()
_view[4]=10

print(a)
print(_view)



[ 1  4  3  2 10  6  7  8]
[ 1  4  3  2 10  6  7  8]


In [79]:
import numpy as fk
a=fk.array([1,2,11,23,6,7,8])
q=a.view()
fk.sort(a)
print(a)
print(q)


[ 1  2 11 23  6  7  8]
[ 1  2 11 23  6  7  8]


In [76]:
fk.sort(q)

array([ 1,  2,  6,  7,  8, 11, 23])

In [77]:
print(a)
print(q)

[ 1  2 11 23  6  7  8]
[ 1  2 11 23  6  7  8]


# shape and reshape

In [5]:
import numpy as khan
a=khan.array([[1,2,3],[4,5,6]])

print(khan.shape(a))


(2, 3)


In [46]:
import numpy as khan
a=khan.array([[[1,2,3],[4,5,6],[6,7,8]]])

print(khan.shape(a))


(1, 3, 3)


In [55]:
import numpy as kha
a=kha.array([1,2,3,4,5,6,4,5,6,4,5,6])
newa=a.reshape(3,2,2)
print(newa)


[[[1 2]
  [3 4]]

 [[5 6]
  [4 5]]

 [[6 4]
  [5 6]]]


In [32]:
import numpy as khan
a=khan.array([1,2,3,4,5,6,7,8,9,10,11,12])
newa=a.reshape(3,2,2)
print(newa)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [34]:
import numpy as khan
a1=khan.array([1,2,3,4])
a2=khan.array([5,6,7,8])
a=khan.concatenate((a1,a2))
print(a)


[1 2 3 4 5 6 7 8]


In [48]:
import numpy as khan
a1=khan.array([[1,2,3,4,2],[1,2,3,4,4]])
a2=khan.array([[3,2,1,4,2],[5,4,3,2,1]])
a=khan.concatenate((a1,a2), axis=1)
print(a)


[[1 2 3 4 2 3 2 1 4 2]
 [1 2 3 4 4 5 4 3 2 1]]


In [49]:
import numpy as khan
a1=khan.array([[1,2,3,4,2],[1,2,3,4,4]])
a2=khan.array([[3,2,1,4,2],[5,4,3,2,1]])
a=khan.stack((a1,a2), axis=1)
print(a)


[[[1 2 3 4 2]
  [3 2 1 4 2]]

 [[1 2 3 4 4]
  [5 4 3 2 1]]]


In [51]:
import numpy as khan
a1=khan.array([[1,2,3,4,2],[1,2,3,4,4]])
a2=khan.array([[3,2,1,4,2],[5,4,3,2,1]])
a=khan.hstack((a1,a2))
print(a)


[[1 2 3 4 2 3 2 1 4 2]
 [1 2 3 4 4 5 4 3 2 1]]


In [54]:
import numpy as khan
a1=khan.array([[1,2,3,4,2],[1,2,3,4,4]])
a2=khan.array([[3,2,1,4,2],[5,4,3,2,1]])
a=khan.dstack((a1,a2))
print(a)


[[[1 3]
  [2 2]
  [3 1]
  [4 4]
  [2 2]]

 [[1 5]
  [2 4]
  [3 3]
  [4 2]
  [4 1]]]


# practice

In [15]:
import numpy as kh
a=kh.array([[[[1,2,3,4],[4,3,2,1,],[8,7,6,5],[11,12,13,14]]]])
print(a)

[[[[ 1  2  3  4]
   [ 4  3  2  1]
   [ 8  7  6  5]
   [11 12 13 14]]]]


In [16]:
a.ndim

4

In [31]:
b=kh.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
w=b.reshape(2,2,4)
print(w)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [34]:
q=kh.stack((w),axis=1)
print(q)

[[[ 1  2  3  4]
  [ 9 10 11 12]]

 [[ 5  6  7  8]
  [13 14 15 16]]]


In [35]:
type(q)

numpy.ndarray

In [36]:
q.itemsize

4

In [37]:
q.size

16

In [44]:
import numpy as w
s=w.array([1,2,3,4,5])
swat=s.view()
swat[2]=10
print(s,swat)


[ 1  2 10  4  5] [ 1  2 10  4  5]
